### ISSUE TITLE
Wont run on python 3.12.2

### ISSUE THREAD

**Issue by 2vw** [revoltchat/revolt.py#71]
**Describe the bug**

revolt.py refuses to install when using python 3.12.2 for some odd reason, as aiohttp and yarn both decide to not want to build themselves 

**To Reproduce**
A small code snippet showing the error

```py
import revolt, json
import asyncio

with open("json/config.json") as f:
    config = json.load(f)

class Client(revolt.Client):
    async def on_message(self, message: revolt.Message):
        if message.content == "hello":
            await message.channel.send("hi how are you")

async def main():
    async with revolt.utils.client_session() as session:
        client = Client(session, config['TOKEN'])
        await client.start()

asyncio.run(main())
```

**Expected behavior**

Meant to install revolt.py 

**Screenshots**
![image](https://github.com/revoltchat/revolt.py/assets/79321788/596e8999-648b-4d37-b47f-2485b9dc4efd)

**Library version**
Access this info via `pip show revolt.py`
latest

**Additional context**

**Comment by 2vw** [comment]
After installing microshits 6gb of bloat, i still end up with this error:

```py
]
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]
‎
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Successfully built revolt.py
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects
```

**Comment by MCausc78** [comment]
try `pip install -U --force-reinstall aiohttp --extra-index-url https://abstractumbra.github.io/pip/`, then `pip install --no-deps revolt.py`

**Comment by 2vw** [comment]
![image](https://github.com/revoltchat/revolt.py/assets/79321788/da0345d2-1123-4a50-a01f-b9a596ccbeb3)

**Comment by MCausc78** [comment]
have you tried `python c:\Users\willi\Desktop\mecharevoltpy\main.py` instead of clicking VSCode "Run" button?

**Comment by 2vw** [comment]
it works, but on running any command / saying `hello` i get errored out
`AttributeError: module 'ulid' has no attribute 'new'`

**Comment by 2vw** [comment]
```py
  File "c:\Users\willi\Desktop\mecharevoltpy\main.py", line 10, in on_message
    await message.channel.send("hi how are you")
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\revolt\messageable.py", line 67, in send
    message = await self.state.http.send_message(await self._get_channel_id(), content, embed_payload, attachments, reply_payload, masquerade_payload, interactions_payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\revolt\http.py", line 146, in send_message
    return await self.request("POST", f"/channels/{channel}/messages", json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\revolt\http.py", line 69, in request
    json["nonce"] = ulid.new().str # type: ignore
                    ^^^^^^^^
AttributeError: module 'ulid' has no attribute 'new'
```

**Comment by MCausc78** [comment]
well thats already revolt.py issue, i recommend doing `pip install --no-deps git+https://github.com/revoltchat/revolt.py@master`

**Comment by Zomatree** [comment]
You installed the wrong ulid library, please ensure you install the correct dependancies.

Please open a new issue or join the support server for any further issues

**Comment by NanoAim** [comment]
Use python 3.10, the latest aiohttp doesnt work well with python 3.12.
